# Use the official .NET image for the base
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Use the official .NET SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["FrogPay.StoreRegistry/FrogPay.StoreRegistry.csproj", "FrogPay.StoreRegistry/"]
RUN dotnet restore "FrogPay.StoreRegistry/FrogPay.StoreRegistry.csproj"
COPY . .
WORKDIR "/src/FrogPay.StoreRegistry"
RUN dotnet build "FrogPay.StoreRegistry.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FrogPay.StoreRegistry.csproj" -c Release -o /app/publish

# Use the base image to run the application
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FrogPay.StoreRegistry.dll"]
